// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/account.dart';
import 'api/config.dart';
import 'api/download.dart';
import 'api/dto.dart';
import 'api/game.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_DownloadManagerPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManagerPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GamePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DownloadManager
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          dynamic raw);

  @protected
  Game
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  Game
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  Game
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, DlcInfo> dco_decode_Map_String_dlc_info_None(dynamic raw);

  @protected
  Map<String, BigInt> dco_decode_Map_String_u_64_None(dynamic raw);

  @protected
  DownloadManager
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          dynamic raw);

  @protected
  Game
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  AccountManager dco_decode_account_manager(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountDto dco_decode_box_autoadd_account_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_box_autoadd_download_progress_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Config dco_decode_config(dynamic raw);

  @protected
  ConfigDto dco_decode_config_dto(dynamic raw);

  @protected
  Dlc dco_decode_dlc(dynamic raw);

  @protected
  DlcDto dco_decode_dlc_dto(dynamic raw);

  @protected
  DlcInfo dco_decode_dlc_info(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw);

  @protected
  GameDto dco_decode_game_dto(dynamic raw);

  @protected
  GameInfo dco_decode_game_info(dynamic raw);

  @protected
  GameInfoDto dco_decode_game_info_dto(dynamic raw);

  @protected
  GamesDbInfoDto dco_decode_games_db_info_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LaunchResultDto dco_decode_launch_result_dto(dynamic raw);

  @protected
  List<Account> dco_decode_list_account(dynamic raw);

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw);

  @protected
  List<Dlc> dco_decode_list_dlc(dynamic raw);

  @protected
  List<DlcDto> dco_decode_list_dlc_dto(dynamic raw);

  @protected
  List<DownloadProgressDto> dco_decode_list_download_progress_dto(dynamic raw);

  @protected
  List<GameDto> dco_decode_list_game_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, DlcInfo)> dco_decode_list_record_string_dlc_info(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountDto? dco_decode_opt_box_autoadd_account_dto(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DownloadProgressDto? dco_decode_opt_box_autoadd_download_progress_dto(
      dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  (String, DlcInfo) dco_decode_record_string_dlc_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserDataDto dco_decode_user_data_dto(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DownloadManager
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          SseDeserializer deserializer);

  @protected
  Game
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  Game
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  Game
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  Map<String, DlcInfo> sse_decode_Map_String_dlc_info_None(
      SseDeserializer deserializer);

  @protected
  Map<String, BigInt> sse_decode_Map_String_u_64_None(
      SseDeserializer deserializer);

  @protected
  DownloadManager
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          SseDeserializer deserializer);

  @protected
  Game
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  AccountManager sse_decode_account_manager(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_box_autoadd_account_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_box_autoadd_download_progress_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Config sse_decode_config(SseDeserializer deserializer);

  @protected
  ConfigDto sse_decode_config_dto(SseDeserializer deserializer);

  @protected
  Dlc sse_decode_dlc(SseDeserializer deserializer);

  @protected
  DlcDto sse_decode_dlc_dto(SseDeserializer deserializer);

  @protected
  DlcInfo sse_decode_dlc_info(SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(
      SseDeserializer deserializer);

  @protected
  GameDto sse_decode_game_dto(SseDeserializer deserializer);

  @protected
  GameInfo sse_decode_game_info(SseDeserializer deserializer);

  @protected
  GameInfoDto sse_decode_game_info_dto(SseDeserializer deserializer);

  @protected
  GamesDbInfoDto sse_decode_games_db_info_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LaunchResultDto sse_decode_launch_result_dto(SseDeserializer deserializer);

  @protected
  List<Account> sse_decode_list_account(SseDeserializer deserializer);

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer);

  @protected
  List<Dlc> sse_decode_list_dlc(SseDeserializer deserializer);

  @protected
  List<DlcDto> sse_decode_list_dlc_dto(SseDeserializer deserializer);

  @protected
  List<DownloadProgressDto> sse_decode_list_download_progress_dto(
      SseDeserializer deserializer);

  @protected
  List<GameDto> sse_decode_list_game_dto(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, DlcInfo)> sse_decode_list_record_string_dlc_info(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountDto? sse_decode_opt_box_autoadd_account_dto(
      SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DownloadProgressDto? sse_decode_opt_box_autoadd_download_progress_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  (String, DlcInfo) sse_decode_record_string_dlc_info(
      SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserDataDto sse_decode_user_data_dto(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          DownloadManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_dlc_info_None(
      Map<String, DlcInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_u_64_None(
      Map<String, BigInt> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
          DownloadManager self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
          Game self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_account_manager(
      AccountManager self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_dto(
      AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_download_progress_dto(
      DownloadProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_config(Config self, SseSerializer serializer);

  @protected
  void sse_encode_config_dto(ConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_dlc(Dlc self, SseSerializer serializer);

  @protected
  void sse_encode_dlc_dto(DlcDto self, SseSerializer serializer);

  @protected
  void sse_encode_dlc_info(DlcInfo self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress_dto(
      DownloadProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_game_dto(GameDto self, SseSerializer serializer);

  @protected
  void sse_encode_game_info(GameInfo self, SseSerializer serializer);

  @protected
  void sse_encode_game_info_dto(GameInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_games_db_info_dto(
      GamesDbInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_launch_result_dto(
      LaunchResultDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_account(List<Account> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_dto(
      List<AccountDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dlc(List<Dlc> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dlc_dto(List<DlcDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_progress_dto(
      List<DownloadProgressDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_game_dto(List<GameDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_dlc_info(
      List<(String, DlcInfo)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_u_64(
      List<(String, BigInt)> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account_dto(
      AccountDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_download_progress_dto(
      DownloadProgressDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_dlc_info(
      (String, DlcInfo) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_u_64(
      (String, BigInt) self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_data_dto(UserDataDto self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_minigalaxy_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManagerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_minigalaxy_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManager =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDownloadManagerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_minigalaxy_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_minigalaxy_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGame =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGamePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
