// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_accounts_file_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_account`, `create_account_from_user_data`, `fetch_user_avatar`, `get_account`, `get_active_account`, `get_all_accounts`, `load`, `remove_account`, `save`, `set_active_account`, `update_avatar`, `update_refresh_token`

/// Represents a user account
class Account {
  final String userId;
  final String username;
  final String? email;
  final String? avatarUrl;
  final String refreshToken;
  final String addedAt;
  final String? lastLogin;

  const Account({
    required this.userId,
    required this.username,
    this.email,
    this.avatarUrl,
    required this.refreshToken,
    required this.addedAt,
    this.lastLogin,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      username.hashCode ^
      email.hashCode ^
      avatarUrl.hashCode ^
      refreshToken.hashCode ^
      addedAt.hashCode ^
      lastLogin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username &&
          email == other.email &&
          avatarUrl == other.avatarUrl &&
          refreshToken == other.refreshToken &&
          addedAt == other.addedAt &&
          lastLogin == other.lastLogin;
}

/// Account manager for multi-account support
class AccountManager {
  final List<Account> accounts;
  final String? activeAccountId;

  const AccountManager({
    required this.accounts,
    this.activeAccountId,
  });

  static Future<AccountManager> default_() =>
      RustLib.instance.api.crateApiAccountAccountManagerDefault();

  @override
  int get hashCode => accounts.hashCode ^ activeAccountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountManager &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          activeAccountId == other.activeAccountId;
}
