// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_default_install_dir`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_ongoing_download`, `add_paused_download`, `get_cache_dir`, `get_config_file_path`, `get_config_games_dir`, `get_data_dir`, `get_icon_dir`, `get_thumbnail_dir`, `load`, `remove_ongoing_download`, `remove_paused_download`, `save`

/// Application configuration
class Config {
  final String locale;
  final String lang;
  final String view;
  final String installDir;
  final String username;
  final String refreshToken;
  final bool keepInstallers;
  final bool stayLoggedIn;
  final bool useDarkTheme;
  final bool showHiddenGames;
  final bool showWindowsGames;
  final bool keepWindowMaximized;
  final bool installedFilter;
  final bool createApplicationsFile;
  final int maxParallelGameDownloads;
  final Int64List currentDownloads;
  final Map<String, BigInt> pausedDownloads;
  final String? activeAccountId;

  const Config({
    required this.locale,
    required this.lang,
    required this.view,
    required this.installDir,
    required this.username,
    required this.refreshToken,
    required this.keepInstallers,
    required this.stayLoggedIn,
    required this.useDarkTheme,
    required this.showHiddenGames,
    required this.showWindowsGames,
    required this.keepWindowMaximized,
    required this.installedFilter,
    required this.createApplicationsFile,
    required this.maxParallelGameDownloads,
    required this.currentDownloads,
    required this.pausedDownloads,
    this.activeAccountId,
  });

  static Future<Config> default_() =>
      RustLib.instance.api.crateApiConfigConfigDefault();

  @override
  int get hashCode =>
      locale.hashCode ^
      lang.hashCode ^
      view.hashCode ^
      installDir.hashCode ^
      username.hashCode ^
      refreshToken.hashCode ^
      keepInstallers.hashCode ^
      stayLoggedIn.hashCode ^
      useDarkTheme.hashCode ^
      showHiddenGames.hashCode ^
      showWindowsGames.hashCode ^
      keepWindowMaximized.hashCode ^
      installedFilter.hashCode ^
      createApplicationsFile.hashCode ^
      maxParallelGameDownloads.hashCode ^
      currentDownloads.hashCode ^
      pausedDownloads.hashCode ^
      activeAccountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          locale == other.locale &&
          lang == other.lang &&
          view == other.view &&
          installDir == other.installDir &&
          username == other.username &&
          refreshToken == other.refreshToken &&
          keepInstallers == other.keepInstallers &&
          stayLoggedIn == other.stayLoggedIn &&
          useDarkTheme == other.useDarkTheme &&
          showHiddenGames == other.showHiddenGames &&
          showWindowsGames == other.showWindowsGames &&
          keepWindowMaximized == other.keepWindowMaximized &&
          installedFilter == other.installedFilter &&
          createApplicationsFile == other.createApplicationsFile &&
          maxParallelGameDownloads == other.maxParallelGameDownloads &&
          currentDownloads == other.currentDownloads &&
          pausedDownloads == other.pausedDownloads &&
          activeAccountId == other.activeAccountId;
}
