// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadProgress`, `DownloadStatus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `calculate_md5`, `cancel_download`, `download_file`, `get_active_downloads`, `get_progress`, `new`, `pause_download`, `verify_checksum`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DownloadManager>>
abstract class DownloadManager implements RustOpaqueInterface {
  static Future<DownloadManager> default_() =>
      RustLib.instance.api.crateApiDownloadDownloadManagerDefault();
}
