// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UserProfileDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Account data for Flutter UI
class AccountDto {
  final String userId;
  final String username;
  final String refreshToken;
  final String? avatarUrl;

  const AccountDto({
    required this.userId,
    required this.username,
    required this.refreshToken,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      username.hashCode ^
      refreshToken.hashCode ^
      avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username &&
          refreshToken == other.refreshToken &&
          avatarUrl == other.avatarUrl;
}

/// Config settings for Flutter UI
class ConfigDto {
  final String locale;
  final String lang;
  final String view;
  final String installDir;
  final bool keepInstallers;
  final bool stayLoggedIn;
  final bool useDarkTheme;
  final bool showHiddenGames;
  final bool showWindowsGames;

  const ConfigDto({
    required this.locale,
    required this.lang,
    required this.view,
    required this.installDir,
    required this.keepInstallers,
    required this.stayLoggedIn,
    required this.useDarkTheme,
    required this.showHiddenGames,
    required this.showWindowsGames,
  });

  @override
  int get hashCode =>
      locale.hashCode ^
      lang.hashCode ^
      view.hashCode ^
      installDir.hashCode ^
      keepInstallers.hashCode ^
      stayLoggedIn.hashCode ^
      useDarkTheme.hashCode ^
      showHiddenGames.hashCode ^
      showWindowsGames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigDto &&
          runtimeType == other.runtimeType &&
          locale == other.locale &&
          lang == other.lang &&
          view == other.view &&
          installDir == other.installDir &&
          keepInstallers == other.keepInstallers &&
          stayLoggedIn == other.stayLoggedIn &&
          useDarkTheme == other.useDarkTheme &&
          showHiddenGames == other.showHiddenGames &&
          showWindowsGames == other.showWindowsGames;
}

/// DLC data for Flutter UI
class DlcDto {
  final PlatformInt64 id;
  final String name;
  final String title;
  final String imageUrl;

  const DlcDto({
    required this.id,
    required this.name,
    required this.title,
    required this.imageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ title.hashCode ^ imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlcDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          title == other.title &&
          imageUrl == other.imageUrl;
}

/// Download progress for Flutter UI
class DownloadProgressDto {
  final PlatformInt64 gameId;
  final String gameName;
  final BigInt downloadedBytes;
  final BigInt totalBytes;
  final BigInt speedBytesPerSec;
  final String status;

  const DownloadProgressDto({
    required this.gameId,
    required this.gameName,
    required this.downloadedBytes,
    required this.totalBytes,
    required this.speedBytesPerSec,
    required this.status,
  });

  @override
  int get hashCode =>
      gameId.hashCode ^
      gameName.hashCode ^
      downloadedBytes.hashCode ^
      totalBytes.hashCode ^
      speedBytesPerSec.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressDto &&
          runtimeType == other.runtimeType &&
          gameId == other.gameId &&
          gameName == other.gameName &&
          downloadedBytes == other.downloadedBytes &&
          totalBytes == other.totalBytes &&
          speedBytesPerSec == other.speedBytesPerSec &&
          status == other.status;
}

/// Game data for Flutter UI
class GameDto {
  final PlatformInt64 id;
  final String name;
  final String url;
  final String installDir;
  final String imageUrl;
  final String platform;
  final String category;
  final List<DlcDto> dlcs;

  const GameDto({
    required this.id,
    required this.name,
    required this.url,
    required this.installDir,
    required this.imageUrl,
    required this.platform,
    required this.category,
    required this.dlcs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      url.hashCode ^
      installDir.hashCode ^
      imageUrl.hashCode ^
      platform.hashCode ^
      category.hashCode ^
      dlcs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          url == other.url &&
          installDir == other.installDir &&
          imageUrl == other.imageUrl &&
          platform == other.platform &&
          category == other.category &&
          dlcs == other.dlcs;
}

/// Game info response
class GameInfoDto {
  final PlatformInt64 id;
  final String title;
  final String? description;
  final String? changelog;

  const GameInfoDto({
    required this.id,
    required this.title,
    this.description,
    this.changelog,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ description.hashCode ^ changelog.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          changelog == other.changelog;
}

/// Games DB info (covers, backgrounds, etc)
class GamesDbInfoDto {
  final String cover;
  final String verticalCover;
  final String background;
  final String summary;
  final String genre;

  const GamesDbInfoDto({
    required this.cover,
    required this.verticalCover,
    required this.background,
    required this.summary,
    required this.genre,
  });

  @override
  int get hashCode =>
      cover.hashCode ^
      verticalCover.hashCode ^
      background.hashCode ^
      summary.hashCode ^
      genre.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GamesDbInfoDto &&
          runtimeType == other.runtimeType &&
          cover == other.cover &&
          verticalCover == other.verticalCover &&
          background == other.background &&
          summary == other.summary &&
          genre == other.genre;
}

/// Launch result
class LaunchResultDto {
  final bool success;
  final String? errorMessage;
  final int? pid;

  const LaunchResultDto({
    required this.success,
    this.errorMessage,
    this.pid,
  });

  @override
  int get hashCode => success.hashCode ^ errorMessage.hashCode ^ pid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchResultDto &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          pid == other.pid;
}

/// User data from GOG
class UserDataDto {
  final String userId;
  final String username;
  final String? email;

  const UserDataDto({
    required this.userId,
    required this.username,
    this.email,
  });

  @override
  int get hashCode => userId.hashCode ^ username.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDataDto &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          username == other.username &&
          email == other.email;
}
