// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `APP_STATE`, `AppState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String getLoginUrl() => RustLib.instance.api.crateApiSimpleGetLoginUrl();

String getRedirectUrl() => RustLib.instance.api.crateApiSimpleGetRedirectUrl();

String getSuccessUrl() => RustLib.instance.api.crateApiSimpleGetSuccessUrl();

Future<String> authenticate({String? loginCode, String? refreshToken}) =>
    RustLib.instance.api.crateApiSimpleAuthenticate(
        loginCode: loginCode, refreshToken: refreshToken);

Future<bool> isLoggedIn() => RustLib.instance.api.crateApiSimpleIsLoggedIn();

Future<void> logout() => RustLib.instance.api.crateApiSimpleLogout();

Future<UserDataDto> getUserData() =>
    RustLib.instance.api.crateApiSimpleGetUserData();

Future<List<AccountDto>> getAllAccounts() =>
    RustLib.instance.api.crateApiSimpleGetAllAccounts();

Future<AccountDto?> getActiveAccount() =>
    RustLib.instance.api.crateApiSimpleGetActiveAccount();

Future<AccountDto> addCurrentAccount({required String refreshToken}) =>
    RustLib.instance.api
        .crateApiSimpleAddCurrentAccount(refreshToken: refreshToken);

Future<bool> switchAccount({required String userId}) =>
    RustLib.instance.api.crateApiSimpleSwitchAccount(userId: userId);

Future<void> removeAccount({required String userId}) =>
    RustLib.instance.api.crateApiSimpleRemoveAccount(userId: userId);

Future<List<GameDto>> getLibrary() =>
    RustLib.instance.api.crateApiSimpleGetLibrary();

Future<GameInfoDto> getGameInfo({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleGetGameInfo(gameId: gameId);

Future<GamesDbInfoDto> getGamesdbInfo({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleGetGamesdbInfo(gameId: gameId);

Future<String> getGameVersion({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleGetGameVersion(gameId: gameId);

Future<bool> checkForUpdate({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleCheckForUpdate(gameId: gameId);

Future<void> startDownload({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleStartDownload(gameId: gameId);

Future<void> pauseDownload({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimplePauseDownload(gameId: gameId);

Future<void> cancelDownload({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleCancelDownload(gameId: gameId);

Future<DownloadProgressDto?> getDownloadProgress(
        {required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleGetDownloadProgress(gameId: gameId);

Future<List<DownloadProgressDto>> getActiveDownloads() =>
    RustLib.instance.api.crateApiSimpleGetActiveDownloads();

Future<GameDto> installGame(
        {required PlatformInt64 gameId, required String installerPath}) =>
    RustLib.instance.api.crateApiSimpleInstallGame(
        gameId: gameId, installerPath: installerPath);

Future<void> uninstallGame({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleUninstallGame(gameId: gameId);

Future<void> installDlc(
        {required PlatformInt64 gameId, required String dlcInstallerPath}) =>
    RustLib.instance.api.crateApiSimpleInstallDlc(
        gameId: gameId, dlcInstallerPath: dlcInstallerPath);

Future<LaunchResultDto> launchGame({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleLaunchGame(gameId: gameId);

Future<LaunchResultDto> launchGameAsync({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleLaunchGameAsync(gameId: gameId);

Future<void> openWineConfig({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleOpenWineConfig(gameId: gameId);

Future<void> openWineRegedit({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleOpenWineRegedit(gameId: gameId);

Future<void> openWinetricks({required PlatformInt64 gameId}) =>
    RustLib.instance.api.crateApiSimpleOpenWinetricks(gameId: gameId);

Future<ConfigDto> getConfig() => RustLib.instance.api.crateApiSimpleGetConfig();

Future<String> getInstallDir() =>
    RustLib.instance.api.crateApiSimpleGetInstallDir();

Future<void> setInstallDir({required String dir}) =>
    RustLib.instance.api.crateApiSimpleSetInstallDir(dir: dir);

Future<String> getLanguage() =>
    RustLib.instance.api.crateApiSimpleGetLanguage();

Future<void> setLanguage({required String lang}) =>
    RustLib.instance.api.crateApiSimpleSetLanguage(lang: lang);

Future<String> getViewMode() =>
    RustLib.instance.api.crateApiSimpleGetViewMode();

Future<void> setViewMode({required String view}) =>
    RustLib.instance.api.crateApiSimpleSetViewMode(view: view);

Future<bool> getDarkTheme() =>
    RustLib.instance.api.crateApiSimpleGetDarkTheme();

Future<void> setDarkTheme({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetDarkTheme(enabled: enabled);

Future<bool> getShowWindowsGames() =>
    RustLib.instance.api.crateApiSimpleGetShowWindowsGames();

Future<void> setShowWindowsGames({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetShowWindowsGames(enabled: enabled);

Future<bool> getKeepInstallers() =>
    RustLib.instance.api.crateApiSimpleGetKeepInstallers();

Future<void> setKeepInstallers({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetKeepInstallers(enabled: enabled);

Future<bool> canConnect() => RustLib.instance.api.crateApiSimpleCanConnect();

List<(String, String)> getSupportedLanguages() =>
    RustLib.instance.api.crateApiSimpleGetSupportedLanguages();

List<(String, String)> getSupportedLocales() =>
    RustLib.instance.api.crateApiSimpleGetSupportedLocales();

List<(String, String)> getViewModes() =>
    RustLib.instance.api.crateApiSimpleGetViewModes();
